[agent]
version = "1.0"
name = "Campaign manager"          
type = "campaign_manager"          
icon = ""

[goal]
goal = "receive_reply"            
completion_events = [
    "email_reply_received",
    "email_reply_not_received",
    "email_not_deliverable"
]

[listeners]
events = [
    "contact_added_to_campaign",
    "email_bounced"
]

[capabilities]
types = [
    "enrich_email_address",
    "validate_email_deliverability",
    "manage_campaign_execution",
    "select_optimal_sending_mailbox",
    "manage_email_delivery_failures",
    "forward_email_replies"
]

[plays]
"contact_added_to_campaign" = [
    "enrich_email_address",
    "validate_email_deliverability",
    "select_optimal_sending_mailbox",
    "manage_campaign_execution",
    "forward_email_replies"
]

"email_bounced" = [
    "manage_email_delivery_failures"
]
