[agent]
version = "1.0"
name = "Email Keeper"
type = "email_keeper"
scope = "personal"
icon = "mail-02"

[goal]
goal = "capture_commercial_email_conversations"
completion_events = [
    "ingest_email",
    "ignore_email",
]

[listeners]
events = [
    "new_email",
]

[capabilities]
types = [
    "classify_email",
    "identify_participants",
    "ingest_email",
    "summarize_message",
    "summarize_thread",
]

[plays]
"new_email" = [
    "classify_email",
    "identify_participants",
    "ingest_email",
    "summarize_message",
    "summarize_thread",
]