[agent]
version = "1.0"
name = "Meeting keeper"          
type = "meeting_keeper"          
scope = "personal"
icon = "notebook-pen"

[goal]
goal = "capture_external_meeting"
completion_events = [
    "meeting_logged"
]

[listeners]
events = [
    "new_meeting_recording"
]

[capabilities]
types = [
    "extract_meeting_highlights",
    "identify_meeting_participants",
    "create_and_enrich_contacts",
    "add_meeting_notes_to_timeline"
]

[plays]
"new_meeting_recording" = [
    "identify_meeting_participants",
    "create_and_enrich_contacts",
    "extract_meeting_highlights",
    "add_meeting_notes_to_timeline"
]
