[agent]
version = "1.0"
name = "Support signal detector"          
type = "support_signal_detector"          
goal = "detect_support_signal"
icon = "life-buoy-01"

[triggers]
events = [
    "web_session.ready_for_analysis"
]

[[capabilities]]
type = "monitor_support_pages"        

[capabilities.config_default]  
support_pages = ["*/support/*"]

[[capabilities]]
type = "apply_tag"                    

[[capabilities.config_default]]
tag_name = "Support"             
tag_entity = "Company"
