[agent]
version = "1.0"
name = "Cashflow Guardian"
description = "Cashflow Guardian helps you get paid on time, every time.  It automates your entire billing process from invoice creation to revenue recognition."
type = "cashflow_guardian"
scope = "workspace"
icon = "shield-dollar"

[goal]
goal = "Get you paid"
metric = "{currencySymbol}{amount} cash collected in the past 30 days"
completion_events = [
    "invoice_paid",
    "invoice_voided"
]

[listeners]
events = [
    "start_invoice_run_with_autopayment",
    "start_invoice_run",
    "send_invoice",
    "invoice_paid",
    "invoice_past_due",
    "invoice_voided",
#    "payment_failed",
]

[capabilities]
types = [
    "generate_invoice",
    "process_autopayment",
    "send_invoice_via_email",
    "send_paid_notification",
    "send_past_due_notification",
    "send_invoice_voided_notification",
#    "send_payment_failure_notification",
#    "sync_invoice_to_accounting_system",
#    "update_invoice_status_in_accounting_system"
]

[plays]
"start_invoice_run" = [
    "generate_invoice",
#    "sync_invoice_to_accounting_system",
]

"send_invoice" = [
    "send_invoice_via_email"
]

"start_invoice_run_with_autopayment" = [
    "generate_invoice",
    "process_autopayment"
#    "sync_invoice_to_accounting_system",
]

"invoice_paid" = [
    "send_paid_notification",
#    "update_invoice_status_in_accounting_system"
]

"invoice_past_due" = [
    "send_past_due_notification"
]

"invoice_voided" = [
    "send_invoice_voided_notification",
#    "update_invoice_status_in_accounting_system"
]

#"payment_failed" = [
#    "send_payment_failure_notification"
#]