[agent]
version = "1.0"
name = "Email Keeper"
description = "Email Keeper automatically captures and summarizes your email conversations. It identifies participants, extracts key highlights, and organizes your emails for easy access."
type = "email_keeper"
scope = "personal"
icon = "mail-01"

[goal]
goal = "Capture and summarize email conversations"
metric = "{count} commercial email conversations captured in the past 30 days"
completion_events = [
    "ingest_email",
    "ignore_email",
]

[listeners]
events = [
    "new_email",
]

[capabilities]
types = [
    "classify_email",
    "identify_email_participants",
    "ingest_email",
    "summarize_message",
    "summarize_thread",
]

[plays]
"new_email" = [
    "classify_email",
    "identify_email_participants",
    "ingest_email",
    "summarize_message",
    "summarize_thread",
]