[agent]
version = "1.0"
name = "ICP Qualifier"
description = "ICP Qualifier accurately evaluates new leads against your Ideal Customer Profile. It automatically researches a company and determines if they are the right fit for your business."
type = "icp_qualifier"          
scope = "workspace"
icon = "target-04"

[goal]
goal = "Evaluate if a company fits your Ideal Customer Profile"
metric = "{count} leads qualified in the past 30 days"
completion_events = [
    "icp_fit",
    "icp_not_a_fit"
]

[listeners]
events = [
    "run_icp_qualifier_agent",
    "new_lead"
] 

[capabilities]
types = [
    "gather_company_intelligence",        
    "evaluate_company_icp_fit",
    "update_company_status" 
]

[plays]
"run_icp_qualifier_agent" = [    
    "gather_company_intelligence",        
    "evaluate_company_icp_fit",
    "update_company_status" 
]

"new_lead" = [    
    "gather_company_intelligence",        
    "evaluate_company_icp_fit",
    "update_company_status" 
]
