[agent]
version = "1.0"
name = "ICP qualifier"
type = "icp_qualifier"          
scope = "workspace"
icon = "target-04"

[goal]
goal = "evaluate_icp_fit"
completion_events = [
    "icp_fit",
    "icp_not_a_fit"
]

[listeners]
events = [
    "run_icp_qualifier_agent",
    "new_lead"
] 

[capabilities]
types = [
    "gather_company_intelligence",        
    "evaluate_company_icp_fit",
    "update_company_status" 
]

[plays]
"run_icp_qualifier_agent" = [    
    "gather_company_intelligence",        
    "evaluate_company_icp_fit",
    "update_company_status" 
]

"new_lead" = [    
    "gather_company_intelligence",        
    "evaluate_company_icp_fit",
    "update_company_status" 
]
