[agent]
version = "1.0"
name = "ICP qualifier"          
type = "icp_qualifier"          
goal = "evaluate_icp_fit"
icon = "target"

[triggers]
events = [
    "company.stage.lead"
] 

[capabilities]
types = [
    "detect_new_lead",
    "gather_company_intelligence",        
    "evaluate_company_icp_fit",
    "update_company_status" 
]
