[agent]
version = "1.0"
name = "LinkedIn networker"          
type = "linkedin_networker"          
goal = "grow_linkedin_audience"
icon = ""

[triggers]
events = [
    "contact.sent_to_agent.linkedin_networker"
]

[[capabilities]]
type = "sync_connections"        

[capabilities.config_default]  
browser_extension_enabled = false
sync_frequency = "daily"

[[capabilities]]
type = "send_connection_requests"        

[capabilities.config_default]  
with_message = false
message = ""

[[capabilities]]
type = "send_linkedin_message"        

[capabilities.config_default]  
message = ""

