[agent]
version = "1.0"
name = "Meeting Keeper"          
description = "Meeting Keeper automatically captures and summarizes your external meetings with customers and prospects. It identifies participants, extracts key highlights, and shares the important details with your team."
type = "meeting_keeper"          
scope = "personal"
icon = "edit-03"

[goal]
goal = "Capture and share external meetings with your team"
metric = "{count} meetings shared in the past 30 days"
completion_events = [
    "meeting_logged"
]

[listeners]
events = [
    "new_meeting_recording"
]

[capabilities]
types = [
    "extract_meeting_highlights",
    "identify_meeting_participants",
    "create_and_enrich_contacts",
    "add_meeting_notes_to_company"
]

[plays]
"new_meeting_recording" = [
    "identify_meeting_participants",
    "create_and_enrich_contacts",
    "extract_meeting_highlights",
    "add_meeting_notes_to_company"
]
