[agent]
version = "1.0"
name = "Support Spotter"          
description = "Support Spotter identifies companies that need help by proactively monitoring customer interactions and meetings. It automatically detects support signals and alerts your team when help is needed."
type = "support_spotter"          
scope = "workspace"
icon = "life-buoy-01"

[goal]
goal = "Flag companies that may need your help"
completion_events = [
    "help_spotted"
]

[listeners]
events = [
    "company_identified",
    "new_meeting_recording",
    "company_needs_help"
]

[capabilities]
types = [
    "detect_support_webvisit",
    "extract_support_signals_from_meeting",
    "apply_tag_to_company",
    "log_requests_for_help"
]

[plays]
"company_identified" = [
    "detect_support_webvisit",
]

"new_meeting_recording" = [
    "extract_support_signals_from_meeting",
    "log_requests_for_help"
]

"company_needs_help" = [
    "apply_tag_to_company"
]
