[agent]
version = "1.0"
name = "Support spotter"          
type = "support_spotter"          
icon = "life-buoy-01"

[goal]
goal = "spot_help_needed"
completion_events = [
    "needs_help",
]

[listeners]
events = [
    "new_support_visit"
]

[capabilities]
types = [
    "apply_tag"
]

[plays]
"new_support_visit" = [
    "apply_tag"
]
