[agent]
version = "1.0"
name = "Support spotter"          
type = "support_spotter"          
scope = "workspace"
icon = "life-buoy-01"

[goal]
goal = "spot_help_needed"
completion_events = [
    "company_needs_help"
]

[listeners]
events = [
    "web_visitor_identified",
    "meeting_logged"
]

[capabilities]
types = [
    "check_support_need",
    "apply_tag"
]

[plays]
"meeting_logged" = [
    "check_support_need",
    "apply_tag"
]
