[agent]
version = "1.0"
name = "Support signal detector"          
type = "support_signal_detector"          
goal = "detect_support_signal"
icon = "life-buoy-01"

[[capabilities]]
type = "monitor_support_pages"        

[capabilities.config_default]  
support_pages = ["*/support/*"]

[[capabilities]]
type = "tag_company"                    

[[capabilities.config_default]]
tag_name = "Support"             
