[agent]
version = "1.0"
name = "Support spotter"          
type = "support_spotter"          
scope = "workspace"
icon = "life-buoy-01"

[goal]
goal = "spot_help_needed"
completion_events = [
    "help_spotted"
]

[listeners]
events = [
    "company_identified",
    "new_meeting_recording",
    "company_needs_help"
]

[capabilities]
types = [
    "detect_support_webvisit",
    "extract_support_signals_from_meeting",
    "apply_tag_to_company"
]

[plays]
"company_identified" = [
    "detect_support_webvisit",
]

"new_meeting_recording" = [
    "extract_support_signals_from_meeting",
]

"company_needs_help" = [
    "apply_tag_to_company"
]
