[agent]
version = "1.0"
name = "Web Visitor Identifier"          
description = "Web Visitor Identifier reveals the companies visiting your website in real-time. It automatically analyzes visitor behavior and notifies your team about potential leads."
type = "web_visitor_identifier"          
scope = "workspace"
icon = "radar"

[goal]
goal = "Identify leads that visit your website"
metric = "{count} visitors identified in the past 30 days"
completion_events = [
    "company_identified",
    "web_visitor_not_identified"
]

[listeners]
events = [
    "new_web_session"
]

[capabilities]
types = [
    "identify_web_visitor",
    "create_and_enrich_company",
    "analyze_web_session_for_intent",
    "send_web_visitor_slack_notification" 
]

[plays]
"new_web_session" = [
    "identify_web_visitor",
    "create_and_enrich_company",
    "analyze_web_session_for_intent", 
    "send_web_visitor_slack_notification" 
]
