[agent]
version = "1.0"
name = "Web visitor identifier"          
type = "web_visitor_identifier"          
goal = "identify_web_visitor"
icon = "radar"

[triggers]
events = [
    "web_session.created"
]

[capabilities]
types = [
    "identify_web_visitor",
    "create_and_enrich_company",
    "analyze_web_session_for_intent",
    "send_web_visitor_slack_notification"
]
